Cysharp/ZLogger

src/ZLogger/ZLogger.csproj

`-directory` argument causes a build error.
```
1>Start to remove nullable reference.
1>-directory
1>Fail in console app running on Program.RemoveNullableReferenceDefine
1>System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Programming\Git\ZLogger\src\ZLogger\-directory'.
1>   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
1>   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
1>   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
1>   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
1>   at …
```

Fix Post-build Event error

---

.github/workflows/stale.yml

close no update, comment issue & pr.
please make `wip` and `stale` label.
* schedule: run 1 time for a day.
* enable issue: true
* enable pr: true
* when: 90 day no update.
* close: past 7 day after stale mark
* ignore execution on label: `wip`
* reset stale when update: true

chore: stale issue which not update

---

.github/workflows/build-debug.yml
.github/workflows/build-release.yml

Please merge after #38 is merged.
* change: ci image update to unityci/editor.
* change: unity ci to build with actions.
* gableroux/unity3d is deprecated and moved to unityci/editor.
* Unity License Activation / Build is handle with actions `game-ci/unity-builder`, no more direct batch mode call.
* ALF/ULF License is not compatible with gableroux/unity3d, new ULF is used in unityci/editor.

chore: new unity build with unityci/editor

---

sandbox/ConsoleApp/Program.cs
src/ZLogger.Unity/Assets/Scripts/ZLogger/ZLoggerExtensions.cs
src/ZLogger/ZLoggerExtensions.cs
src/ZLogger/ZLoggerExtensions.tt

I found that the same problem as #11 occurred in ZLog and ZLogWithPayload.
I referred to commit 8256b53 for how to fix it.

Avoid FormatException on ZLog and ZLogWithPayload

---

src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/LogStates/InterpolatedStringLogState.cs
src/ZLogger/ZLoggerInterpolatedStringHandler.LogLevel.cs
src/ZLogger/ZLoggerInterpolatedStringHandler.LogLevel.tt

Fixed the following two minor issues:
- ParameterCount not being set in InterpolatedStringLogState
- Problem that `AppendFormatted<T>(Nullable<T> ...)` is not called

Fix bugs for LogState

---

ZLogger.Generator/ZLogger.Generator/ZLoggerGenerator.Emitter.cs
sandbox/GeneratorSandbox/GeneratedMock.cs
src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/Formatters/SystemTextJsonZLoggerFormatter.cs
src/ZLogger/IKeyNameMutator.cs
src/ZLogger/IZLoggerFormattable.cs
src/ZLogger/Internal/CallerArgumentExpressionParser.cs
src/ZLogger/Internal/MagicalBox.cs
src/ZLogger/LogStates/InterpolatedStringLogState.cs
src/ZLogger/LogStates/StringFormatterLogState.cs
src/ZLogger/ZLoggerEntry.cs
src/ZLogger/ZLoggerInterpolatedStringHandler.cs
src/ZLogger/ZLoggerOptions.cs
tests/ZLogger.MessagePack.Tests/FormatterTest.cs
tests/ZLogger.Tests/InterpolatedStringParameterTest.cs
tests/ZLogger.Tests/MessageTest.cs
tests/ZLogger.Tests/ZLogger.Tests.csproj

- Parse the string `[CallerExpressionArgument]`
- Detect parameter names as follows:
- `Context.RequestId` →  `RequestId`
- `Collection.Count(....)` → `Count`
- Add a`KeyNameMutator` option to ZLoggerOptions.
- Make it possible to mutate with the lower case.

Add default behavior of parameter key name 

---

src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger.MessagePack/ZLogger.MessagePack.csproj
tests/ZLogger.MessagePack.Tests/FormatterTest.cs
tests/ZLogger.Tests/EnumDictionaryTest.cs

This PR slightly improve a large number of inefficient if branches.

Fix inefficient branching in MessagePackZLoggerFormatter

---

sandbox/Benchmark/Benchmarks/WriteToFile.cs
src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/AsyncProcessZLogger.cs
src/ZLogger/IZLoggerFormattable.cs
src/ZLogger/IZLoggerState.cs
src/ZLogger/LogStates/InterpolatedStringLogState.cs
src/ZLogger/LogStates/StringFormatterLogState.cs
src/ZLogger/ZLoggerEntry.cs
src/ZLogger/ZLoggerExtensions.cs
src/ZLogger/ZLoggerInterpolatedStringHandler.LogLevel.cs
src/ZLogger/ZLoggerInterpolatedStringHandler.LogLevel.tt

This PR makes log state resource release a reference counting method as follows.
1. state is created. `+1`
2. (N times) each ZLogger provider posts to background worker. `+1`
3. (N times) each ZLogger provider finishes a i/o write. `-1`
4. After finishing the Logger.Log call (all Post calls should be finished). `-1`

Make the log state to manage by reference counting

---

src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/Formatters/SystemTextJsonZLoggerFormatter.cs
src/ZLogger/LogInfo.cs
src/ZLogger/ZLoggerOptions.cs
tests/ZLogger.MessagePack.Tests/FormatterTest.cs
tests/ZLogger.Tests/JsonFormatTest.cs
tests/ZLogger.Tests/PlainTextFormatTest.cs

Make it easier selection of LogInfo properties to be render by flags.
```csharp
options.IncludeProperties = LogInfoProperties.LogLevel | 
LogInfoProperties.Timestamp |
LogInfoProperties.EventIdValue
```

Add an option to easy set the output log infos

---

src/ZLogger/ZLoggerInterpolatedStringHandler.cs
tests/ZLogger.Tests/PlainTextFormatTest.cs

For example:
```csharp
var array = new [] { 1,2,3 };
logger.ZLogInformation($"ids: {array}");
// #=> "ids: 1, 2, 3"
```

Support collection destructuring in the log message

---

sandbox/Benchmark/Benchmarks/PostLogEntry.cs
sandbox/Benchmark/Benchmarks/WriteJsonToConsole.cs
sandbox/Benchmark/Benchmarks/WriteJsonToFile.cs
sandbox/Benchmark/Benchmarks/WritePlainTextToConsole.cs
sandbox/Benchmark/Benchmarks/WritePlainTextToFile.cs
sandbox/Benchmark/Formatters.cs

Fix the settings of other libraries used for benchmarking. 
Also, make a few adjustments to ensure the same conditions as ZLogger.
- NLog
- NLog's AsyncTargetWrapper ignores messages that exceed the queueLimit by default.
- https://github.com/NLog/NLog/wiki/AsyncWrapper-target
- -> `AsyncTargetWrapperOverflowAction`  set to `.Grow`.
- -> `queueLimit` set to default (10000). 
- Serilog
-  Serilog's BackgroundWorkerSink also drops messages that exceed the bufferSize.
- -> `bufferSize` set to max value.
- If bufferSize is exceeded, there are only two choices: drop or block the Log write side. Therefore, `blockWhenFull` is set to false (default) and bufferSize is increased.
- NLog
- refs
- AsyncTargetWrapper
- https://github.com/NLog/NLog/wiki/AsyncWrapper-target
- FileTarget
- …

Fix benchmark settings

---

src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/Formatters/SystemTextJsonZLoggerFormatter.cs
src/ZLogger/ZLoggerOptions.cs
tests/ZLogger.MessagePack.Tests/FormatterTest.cs
tests/ZLogger.Tests/JsonFormatTest.cs

For IncludeProperties in theoptions, `.None` was added because it was not possible to specify that nothing was to be logged.
In addition,
- this option is not useful in PlainTextFormatter, it has been moved to each formatter.

Add LogInfoProperties.None

---

src/ZLogger.MessagePack/Internal/Shims/BitOperations.cs
src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger.MessagePack/ZLogger.MessagePack.csproj
src/ZLogger/Internal/EnumDictionary.cs
src/ZLogger/Internal/MagicalBox.cs
src/ZLogger/Internal/Shims/CollectionsMarshal.cs
src/ZLogger/Internal/Shims/DefaultInterpolatedStringHandler.cs
src/ZLogger/Internal/UnsafeListHelper.cs
src/ZLogger/ZLogger.csproj
src/ZLogger/ZLoggerInterpolatedStringHandler.cs

netstandard2.1 was added to the target.
The following items were missing from the runtime,  so some shims added.
- For following attributes, added PolySharp.
- `[IsExternalInit]`
- Primary constructor seems to use this.
- `[CallerArgumentExpression]`
- `DefaultInterpolatedStringHandler`
- Ported from dotnet/runtime
- `CollectionsMarshal.AsSpan(List<>)`
- Add an substitute method and branch with #if.
- `HashCode.AddBytes` 
- Add a ported implementation and branch with #if.

Add netstandard2.1 to the targets

---

src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/Formatters/SystemTextJsonZLoggerFormatter.cs
src/ZLogger/LogInfo.cs
src/ZLogger/LogScopeState.cs
src/ZLogger/ZLoggerEntry.cs
src/ZLogger/ZLoggerLogger.cs

Change `ZLoggerEntry.ScopeState` -> `ZLoggerEntry.LogInfo.ScopeState`
LogInfo can be handled by users through PrefixFormatter etc.

Move ScopeState into LogInfo

---

sandbox/Benchmark/Benchmark.csproj
sandbox/Benchmark/Benchmarks/WriteJsonToConsole.cs
sandbox/Benchmark/Benchmarks/WriteJsonToFile.cs
sandbox/Benchmark/Benchmarks/WritePlainTextToConsole.cs
sandbox/Benchmark/Benchmarks/WritePlainTextToFile.cs

Hello,
I don't know if you've heard of [ZeroLog](https://github.com/Abc-Arbitrage/ZeroLog): it's a very similar library to ZLogger. Both projects aim to be fast and zero-allocation logging libraries.
I'm one of the authors of ZeroLog, so when I've seen your tweet about ZLogger v2, I was naturally interested in comparing both projects, so I added ZeroLog to your suite of benchmarks.
I thought you could be interested as well, so I'm sharing these here. 🙂
---
TL;DR:
- For file logging, ZeroLog sits between ZLogger's standard and source-generated APIs
- For console logging, ZeroLog seems very slow, I may need to take a look at this I suppose
Here's an example result of `WritePlainTextToFile`:
```
BenchmarkDotNet v0.13.10, Windows 11 (10.0.22631.2715/23H2/2023Update/SunValley3)
13th Gen Intel …
```

Add ZeroLog to benchmarks

---

src/ZLogger.Generator/ZLoggerGenerator.Emitter.cs
tests/ZLogger.Generator.Tests/AttributeTest.cs

Fix error when EventName is passed to constructor of `ZLoggerMessageAttribute`.
before
```cs
public partial void EventName(global::Microsoft.Extensions.Logging.ILogger logger, int x, int y)
{
if (!logger.IsEnabled(LogLevel.Warning)) return;
logger.Log(
LogLevel.Warning,
new EventId(12, EventName), // <-- "EventName" is not string
new EventNameState(x, y),
null,
(state, ex) => state.ToString()
);
}
```
after
```cs
public partial void EventName(global::Microsoft.Extensions.Logging.ILogger logger, int x, int y)
{
if (!logger.IsEnabled(LogLevel.Warning)) return;
logger.Log(
LogLevel.Warning,
new EventId(12, "EventName"),
new EventNameState(x, y),
null,
(state, ex) => state.ToString()
);
}
```

Fix code generation by ZLoggerMessage

---

src/ZLogger.Generator/ZLoggerGenerator.Emitter.cs
tests/ZLogger.Generator.Tests/AttributeTest.cs

```cs
// Generation source
[ZLoggerMessage(LogLevel.Error, "Hello {str} {x}")]
public partial void ErrNullable(ILogger logger, string? str, int? x, Exception? exception = null);
```
before
after

Add nullable annotation to generated code

---

sandbox/GeneratorSandbox/GeneratedMock.cs
src/ZLogger.Generator/ZLoggerGenerator.Emitter.cs
src/ZLogger.Generator/ZLoggerGenerator.Parser.cs
src/ZLogger/IZLoggerFormattable.cs
src/ZLogger/LogInfo.cs
src/ZLogger/LogStates/InterpolatedStringLogState.cs
src/ZLogger/LogStates/StringFormatterLogState.cs
src/ZLogger/ZLoggerEntry.cs
src/ZLogger/ZLoggerExtensions.cs
src/ZLogger/ZLoggerExtensions.tt
src/ZLogger/ZLoggerLogger.cs
tests/ZLogger.Generator.Tests/GenerateTest.cs
tests/ZLogger.Tests/CallerInfoTest.cs
tests/ZLogger.Tests/InterpolatedManyTypesTest.cs
tests/ZLogger.Tests/JsonFormatTest.cs
tests/ZLogger.Tests/NamedParamTest.cs
tests/ZLogger.Tests/PlainTextFormatTest.cs
tests/ZLogger.Tests/ScopeTest.cs
tests/ZLogger.Tests/TestHelpers.cs

#140 
Add the following arguments to the ZLog method to support compiler tracing of callers.
- `[CallerMemberName]`
- `[CallerFilePath]`
- `[CallerLineNumber]`

Support caller informations

---

src/ZLogger.Unity/Assets/ZLogger.Unity/Runtime/UnityDebugLogState.cs

fixes 
```
\Runtime\UnityDebugLogState.cs(8,29): error CS0535: 'UnityDebugLogState' does not implement interface member 'IZLoggerEntryCreatable.CreateEntry(in LogInfo)'
```

Fix not correct implementation CreateEntry which causes compile errors

---

src/ZLogger/ZLogger.csproj

For reasons other than functional requirements, make sure that license files are included in the build .
We have some kind of EmbeddedResource in the dll,
If dll has some kind of EmbeddedResource,
IL2CPP will create a `{Package}.dll-resources.dat` file.

Make sure that resources.dat files are included in the build

---

README.md

I could not get it to work with just "10" as language version in Visual Studio Pro 2022 Version 17.10.0.
Using "10.0" fixed the error for me

Fixed language version for props file

---

sandbox/ConsoleApp/SampleCustomFormatter.cs
src/ZLogger.MessagePack/MessagePackZLoggerFormatter.cs
src/ZLogger/Formatters/PlainTextZLoggerFormatter.cs
src/ZLogger/Formatters/SystemTextJsonZLoggerFormatter.cs
src/ZLogger/IZLoggerFormatter.cs
src/ZLogger/Internal/CodeGeneratorUtil.cs
src/ZLogger/Internal/EnumDictionary.cs
src/ZLogger/Internal/MagicalBox.cs
src/ZLogger/LogStates/InterpolatedStringLogState.cs
src/ZLogger/LogStates/StringFormatterLogState.cs
src/ZLogger/ZLogger.csproj
src/ZLogger/ZLoggerInterpolatedStringHandler.LogLevel.cs
src/ZLogger/ZLoggerInterpolatedStringHandler.cs

Fixes #156
Hello there ☺️
This PR is attempting to fix the crash/incompatibility with NativeAOT:
- Breaking change for `IZLoggerFormatter` which shouldn't be an issue. In all the call sites of `FormatLogEntry`, `TEntry` is always `IZLoggerEntry` and not an actual value type, so forcing `IZLoggerEntry` on the interface will avoid the crash at NativeAOT runtime `Failed to create generic virtual method implementation` (In general, it's better to avoid generic method with generic parameters in interfaces):
```diff
public interface IZLoggerFormatter
{
bool WithLineBreak { get; }
-      void FormatLogEntry<TEntry>(IBufferWriter<byte> writer, TEntry entry)
-           where TEntry : IZLoggerEntry;
+      void FormatLogEntry(IBufferWriter<byte> writer, IZLoggerEntry entry);
}
```
- Add several …

Fix NativeAOT and remove warnings

---

sandbox/Benchmark/Benchmark.csproj
sandbox/Benchmark/Benchmarks/WriteJsonToConsole.cs
sandbox/Benchmark/Benchmarks/WriteJsonToFile.cs
sandbox/Benchmark/Benchmarks/WritePlainTextToConsole.cs
sandbox/Benchmark/Benchmarks/WritePlainTextToFile.cs

This PR updates ZeroLog in benchmarks and replaces some usages of its `LogManager.Shutdown` method with `LogManager.Flush`.
When I sent #127, I made a note that we should expose a `Flush` method for benchmarking, as I had to use `Shutdown`, which worked but was incorrect (it allocates, takes a longer time, does more than necessary, etc). We were using an internal `WaitUntilQueueIsEmpty` method in ZeroLog benchmarks but I couldn't use it here. Oops. 😅
This PR therefore uses the new `Flush` method where it is the correct thing to do. Benchmark results are barely affected though.

Use `ZeroLog.LogManager.Flush()` in benchmarks

---

src/ZLogger/LogInfo.cs
src/ZLogger/ZLoggerLogger.cs
src/ZLogger/ZLoggerOptions.cs
tests/ZLogger.Tests/CallerInfoTest.cs

We have a use case to know which thread generated a log entry. The use of `IAsyncLogProcessor` alongside `System.Threading.Channels` means this has to be done when the `LogInfo` is generated rather than in the reader thread
Cleaned up some minor use of `is` combined with casting, which is not needed these days

Capture caller's thread information into `LogInfo`

---

src/ZLogger/AsyncStreamLineMessageWriter.cs
src/ZLogger/Providers/ZLoggerConsoleLoggerProvider.cs

Fix thread safe issue about console output

---

src/ZLogger/Formatters/SystemTextJsonZLoggerFormatter.cs
tests/ZLogger.Tests/JsonFormatTest.cs

After fixing #184, some characters are still escaped.
Examples: <, >, +

Fix HTML-sensitive characters (like '<' and '>') are escaped

---

src/ZLogger.Generator/DiagnosticDescriptors.cs

Changed the word paramter to parameter

Fixing typo in ZLOG009 messageFormat parameter

---

src/ZLogger/ZLoggerInterpolatedStringHandler.cs

Fix for ZLOG0191, where ISpanFormattable was not supported by Unity's C# version, leading to their being no way to make
ZLoggerInterpolatedStringHandler use stringWriter.AppendFormatted for IEnumerables (and crashing trying to use AppendAsJson)

ZLOG0191: Use IFormattable instead of ISpanFormattable
